### ISSUE TITLE
Does not support non-pin based "Just Works" Simple Secure Bluetooth Pairing 

### ISSUE THREAD

**Issue by deexe001** [felis/USB_Host_Shield_2.0#250] opened 2016-07-25 17:02 UTC
With any HID bluetooth device that is not capable of inputing a pin (such as any bluetooth shutter buttons) the pairing hangs at "Send HID Control Connection Request".

**Comment by Lauszus** [comment] 2016-09-11 21:06
Duplicate of #182.

**Closed by Lauszus** 2016-09-11 21:06 UTC
