### ISSUE TITLE
AfterGlow PS3 Controller

### ISSUE THREAD

**Issue by drsmall** [felis/USB_Host_Shield_2.0#265] opened 2016-10-28 05:22 UTC
So I'm using a wireless AfterGLow PS3 controller. It is wireless via a 2.4ghz connection.
After setting the correct VID and PID, I was able to connect successfully, but the button mapping is all messed up. Moving left stick causes PS, Triangle, Circle, L1, R1 etc to all fire randomly. Pressing Left triggers Select and Start. Things like that. I'm using PS3USBCustom. Is there an easy fix to this? Or do I need to remap everything?

**Comment by Lauszus** [comment] 2016-10-29 01:50
Yeah you will have to write a new driver for it if the mapping is different.

**Comment by drsmall** [comment] 2016-10-29 18:28
Does the library have a function that can give me the hex value of the button being pressed?

**Comment by drsmall** [comment] 2016-10-29 22:12
The more I think about it, the more I feel something else is afoot. I mean a ps3 controller is a ps3 controller. So it should use the same data mappings. Since it's a wireless controller, could it be adding an additional piece of data when it transmits. Maybe something like that is the issue?

**Comment by Lauszus** [comment] 2016-10-29 22:16
Just use ```Serial.print(val, HEX);``` or you can also use ```PrintHex<uint8_t > (val, 0x80);```.

It might be using the Bluetooth mapping. Please see the following comment: https://github.com/felis/USB_Host_Shield_2.0/blob/master/PS3Enums.h#L90. Try to remove it all the places where is says ```-9``` i.e: https://github.com/felis/USB_Host_Shield_2.0/blob/master/PS3USB.cpp#L328, https://github.com/felis/USB_Host_Shield_2.0/blob/master/PS3USB.cpp#L336, and https://github.com/felis/USB_Host_Shield_2.0/blob/master/PS3USB.cpp#L361.

**Comment by xxxajk** [comment] 2016-10-29 22:16
Well, yes, and no...
Yes a USB joystick class has a mapping list in the device.
No, UHS2 doesn't use it. IMHO this is a design flaw, BUT it was the only way to get it to work on RAM starved microcontrollers.

**Comment by drsmall** [comment] 2016-10-29 22:35
@Lauszus that didn't change anything, which is strange. I figured that make something break or at least change the behavior.

**Comment by Lauszus** [comment] 2016-10-31 04:22
You should uncomment this line: https://github.com/felis/USB_Host_Shield_2.0/blob/master/PS3USB.cpp#L21 then. It allows you to see the raw incoming data, then you should be able to map the data yourself.

**Comment by Lauszus** [comment] 2017-10-12 15:59
Closing this, as I believe the issue is solved.

**Closed by Lauszus** 2017-10-12 15:59 UTC
